// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oypuvyflernlqajkljbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95cHV2eWZsZXJubHFhamtsamJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NTM2MzIsImV4cCI6MjA2MjIyOTYzMn0.uLDtohnm6NEDd53zCp2NUHNz6gkX3UEmk9-0NMTiLbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);